apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi
  ports:
  - port: {{ .Values.fastapi.port }}
    targetPort: {{ .Values.fastapi.port }}
  type: ClusterIP
